// 初始化数据文件 - 用于填充硬编码的测试数据

// 生成唯一ID的辅助函数
const generateId = () => Date.now().toString(36) + Math.random().toString(36).substr(2)

// 获取日期字符串（YYYY-MM-DD）
const getDateString = (daysAgo: number = 0) => {
  const date = new Date()
  date.setDate(date.getDate() - daysAgo)
  return date.toISOString().split('T')[0]
}

// 获取日期时间字符串（ISO格式）
const getDateTimeString = (daysAgo: number = 0) => {
  const date = new Date()
  date.setDate(date.getDate() - daysAgo)
  return date.toISOString()
}

// ========== 供应商和客户初始数据 ==========
export const initSuppliers = () => [
  {
    id: 'supplier-001',
    name: '浙江纺织有限公司',
    code: 'SUP001',
    contactPerson: '张经理',
    phone: '13800138001',
    address: '浙江省杭州市余杭区纺织路123号',
    type: '厂家' as const,
    settlementCycle: '月结' as const,
    status: '合作中' as const,
    remark: '主要供应商',
    createdAt: getDateTimeString(90),
    updatedAt: getDateTimeString(30),
  },
  {
    id: 'supplier-002',
    name: '江苏纱线厂',
    code: 'SUP002',
    contactPerson: '李主任',
    phone: '13800138002',
    address: '江苏省苏州市工业园区纱线路456号',
    type: '厂家' as const,
    settlementCycle: '现结' as const,
    status: '合作中' as const,
    createdAt: getDateTimeString(60),
    updatedAt: getDateTimeString(15),
  },
  {
    id: 'supplier-003',
    name: '上海贸易公司',
    code: 'SUP003',
    contactPerson: '王总',
    phone: '13800138003',
    address: '上海市浦东新区贸易路789号',
    type: '贸易商' as const,
    settlementCycle: '季结' as const,
    status: '合作中' as const,
    createdAt: getDateTimeString(45),
    updatedAt: getDateTimeString(10),
  },
  {
    id: 'supplier-004',
    name: '山东染色加工厂',
    code: 'SUP004',
    contactPerson: '赵厂长',
    phone: '13800138004',
    address: '山东省青岛市染色路321号',
    type: '厂家' as const,
    settlementCycle: '月结' as const,
    status: '合作中' as const,
    remark: '染色加工合作厂家',
    createdAt: getDateTimeString(30),
    updatedAt: getDateTimeString(5),
  },
]

export const initCustomers = () => [
  {
    id: 'customer-001',
    name: '北京服装有限公司',
    code: 'CUS001',
    contactPerson: '陈经理',
    phone: '13900139001',
    address: '北京市朝阳区服装街111号',
    type: '直客' as const,
    creditLimit: 500000,
    status: '正常' as const,
    remark: '重要客户',
    createdAt: getDateTimeString(80),
    updatedAt: getDateTimeString(25),
  },
  {
    id: 'customer-002',
    name: '广东批发商行',
    code: 'CUS002',
    contactPerson: '刘老板',
    phone: '13900139002',
    address: '广东省广州市批发市场222号',
    type: '经销商' as const,
    creditLimit: 300000,
    status: '正常' as const,
    createdAt: getDateTimeString(70),
    updatedAt: getDateTimeString(20),
  },
  {
    id: 'customer-003',
    name: '深圳纺织贸易公司',
    code: 'CUS003',
    contactPerson: '周经理',
    phone: '13900139003',
    address: '广东省深圳市南山区贸易路333号',
    type: '经销商' as const,
    creditLimit: 200000,
    status: '正常' as const,
    createdAt: getDateTimeString(50),
    updatedAt: getDateTimeString(15),
  },
]

// ========== 商品初始数据 ==========
export const initProducts = () => [
  {
    id: 'product-001',
    name: '32支棉纱',
    code: 'PROD001',
    specification: '32支',
    composition: '100%棉',
    count: '32s',
    unit: 'kg',
    type: '原料' as const,
    isWhiteYarn: true,
    description: '优质32支纯棉纱线，适用于各种纺织加工',
    createdAt: getDateTimeString(100),
    updatedAt: getDateTimeString(50),
  },
  {
    id: 'product-002',
    name: '40支精梳棉纱',
    code: 'PROD002',
    specification: '40支',
    composition: '100%精梳棉',
    count: '40s',
    unit: 'kg',
    type: '原料' as const,
    isWhiteYarn: true,
    description: '高品质40支精梳棉纱，质地柔软细腻',
    createdAt: getDateTimeString(95),
    updatedAt: getDateTimeString(45),
  },
  {
    id: 'product-003',
    name: '染色32支棉纱',
    code: 'PROD003',
    specification: '32支',
    composition: '100%棉',
    count: '32s',
    unit: 'kg',
    type: '成品' as const,
    isWhiteYarn: false,
    description: '32支染色棉纱，多种颜色可选',
    createdAt: getDateTimeString(80),
    updatedAt: getDateTimeString(40),
  },
]

// ========== 色号初始数据 ==========
export const initColors = () => [
  // product-001 (白坯) 不需要色号
  // product-002 (白坯) 不需要色号
  // product-003 (染色成品) 的色号
  {
    id: 'color-001',
    productId: 'product-003',
    code: 'COL-001',
    name: '天蓝色',
    colorValue: '#87CEEB',
    status: '在售' as const,
  },
  {
    id: 'color-002',
    productId: 'product-003',
    code: 'COL-002',
    name: '粉红色',
    colorValue: '#FFC0CB',
    status: '在售' as const,
  },
  {
    id: 'color-003',
    productId: 'product-003',
    code: 'COL-003',
    name: '米白色',
    colorValue: '#F5F5DC',
    status: '在售' as const,
  },
  {
    id: 'color-004',
    productId: 'product-003',
    code: 'COL-004',
    name: '浅灰色',
    colorValue: '#D3D3D3',
    status: '在售' as const,
  },
]

// ========== 缸号初始数据 ==========
export const initBatches = () => [
  // product-001 (白坯32支) 的缸号
  {
    id: 'batch-001',
    colorId: '', // 白坯不需要色号
    code: 'GH-2024-001',
    productionDate: getDateString(60),
    supplierId: 'supplier-001',
    supplierName: '浙江纺织有限公司',
    purchasePrice: 28.5,
    initialQuantity: 1000,
    stockQuantity: 850,
    stockLocation: 'A区-01-01',
    remark: '优质白坯纱线',
  },
  {
    id: 'batch-002',
    colorId: '',
    code: 'GH-2024-002',
    productionDate: getDateString(45),
    supplierId: 'supplier-001',
    supplierName: '浙江纺织有限公司',
    purchasePrice: 29.0,
    initialQuantity: 1200,
    stockQuantity: 1200,
    stockLocation: 'A区-01-02',
  },
  {
    id: 'batch-003',
    colorId: '',
    code: 'GH-2024-003',
    productionDate: getDateString(30),
    supplierId: 'supplier-002',
    supplierName: '江苏纱线厂',
    purchasePrice: 28.8,
    initialQuantity: 800,
    stockQuantity: 800,
    stockLocation: 'A区-01-03',
  },
  // product-002 (白坯40支) 的缸号
  {
    id: 'batch-004',
    colorId: '',
    code: 'GH-2024-004',
    productionDate: getDateString(50),
    supplierId: 'supplier-002',
    supplierName: '江苏纱线厂',
    purchasePrice: 35.0,
    initialQuantity: 900,
    stockQuantity: 720,
    stockLocation: 'A区-02-01',
  },
  {
    id: 'batch-005',
    colorId: '',
    code: 'GH-2024-005',
    productionDate: getDateString(35),
    supplierId: 'supplier-002',
    supplierName: '江苏纱线厂',
    purchasePrice: 35.5,
    initialQuantity: 1000,
    stockQuantity: 1000,
    stockLocation: 'A区-02-02',
  },
  // product-003 (染色成品) 的缸号
  {
    id: 'batch-006',
    colorId: 'color-001',
    code: 'GH-2024-006',
    productionDate: getDateString(40),
    supplierId: 'supplier-001',
    supplierName: '浙江纺织有限公司',
    purchasePrice: 32.0,
    initialQuantity: 500,
    stockQuantity: 350,
    stockLocation: 'B区-01-01',
  },
  {
    id: 'batch-007',
    colorId: 'color-002',
    code: 'GH-2024-007',
    productionDate: getDateString(35),
    supplierId: 'supplier-001',
    supplierName: '浙江纺织有限公司',
    purchasePrice: 33.0,
    initialQuantity: 600,
    stockQuantity: 450,
    stockLocation: 'B区-01-02',
  },
  {
    id: 'batch-008',
    colorId: 'color-003',
    code: 'GH-2024-008',
    productionDate: getDateString(25),
    supplierId: 'supplier-001',
    supplierName: '浙江纺织有限公司',
    purchasePrice: 31.5,
    initialQuantity: 700,
    stockQuantity: 600,
    stockLocation: 'B区-01-03',
  },
]

// ========== 进货单初始数据 ==========
export const initPurchaseOrders = () => [
  {
    id: 'purchase-001',
    orderNumber: 'PO20241215001',
    supplierId: 'supplier-001',
    supplierName: '浙江纺织有限公司',
    purchaseDate: getDateString(60),
    expectedDate: getDateString(58),
    items: [
      {
        id: 'item-001',
        productId: 'product-001',
        productName: '32支棉纱',
        productCode: 'PROD001',
        colorId: '',
        colorName: '',
        colorCode: '',
        batchCode: 'GH-2024-001',
        quantity: 1000,
        unit: 'kg',
        price: 28.5,
        amount: 28500,
        productionDate: getDateString(60),
        stockLocation: 'A区-01-01',
      },
    ],
    totalAmount: 28500,
    paidAmount: 15000,
    unpaidAmount: 13500,
    status: '已入库' as const,
    operator: '张三',
    remark: '首次采购',
    createdAt: getDateTimeString(60),
    updatedAt: getDateTimeString(60),
  },
  {
    id: 'purchase-002',
    orderNumber: 'PO20241220002',
    supplierId: 'supplier-001',
    supplierName: '浙江纺织有限公司',
    purchaseDate: getDateString(45),
    expectedDate: getDateString(43),
    items: [
      {
        id: 'item-002',
        productId: 'product-001',
        productName: '32支棉纱',
        productCode: 'PROD001',
        colorId: '',
        colorName: '',
        colorCode: '',
        batchCode: 'GH-2024-002',
        quantity: 1200,
        unit: 'kg',
        price: 29.0,
        amount: 34800,
        productionDate: getDateString(45),
        stockLocation: 'A区-01-02',
      },
    ],
    totalAmount: 34800,
    paidAmount: 34800,
    unpaidAmount: 0,
    status: '已入库' as const,
    operator: '李四',
    createdAt: getDateTimeString(45),
    updatedAt: getDateTimeString(44),
  },
  {
    id: 'purchase-003',
    orderNumber: 'PO20241225003',
    supplierId: 'supplier-002',
    supplierName: '江苏纱线厂',
    purchaseDate: getDateString(30),
    expectedDate: getDateString(28),
    items: [
      {
        id: 'item-003',
        productId: 'product-001',
        productName: '32支棉纱',
        productCode: 'PROD001',
        colorId: '',
        colorName: '',
        colorCode: '',
        batchCode: 'GH-2024-003',
        quantity: 800,
        unit: 'kg',
        price: 28.8,
        amount: 23040,
        productionDate: getDateString(30),
        stockLocation: 'A区-01-03',
      },
    ],
    totalAmount: 23040,
    paidAmount: 0,
    unpaidAmount: 23040,
    status: '草稿' as const,
    operator: '王五',
    remark: '草稿',
    createdAt: getDateTimeString(30),
    updatedAt: getDateTimeString(30),
  },
  {
    id: 'purchase-004',
    orderNumber: 'PO20241228004',
    supplierId: 'supplier-002',
    supplierName: '江苏纱线厂',
    purchaseDate: getDateString(5),
    items: [
      {
        id: 'item-004',
        productId: 'product-002',
        productName: '40支精梳棉纱',
        productCode: 'PROD002',
        colorId: '',
        colorName: '',
        colorCode: '',
        batchCode: 'GH-2024-005',
        quantity: 1000,
        unit: 'kg',
        price: 35.5,
        amount: 35500,
        productionDate: getDateString(5),
      },
    ],
    totalAmount: 35500,
    paidAmount: 0,
    unpaidAmount: 35500,
    status: '草稿' as const,
    operator: '赵六',
    createdAt: getDateTimeString(5),
    updatedAt: getDateTimeString(5),
  },
]

// ========== 销售单初始数据 ==========
export const initSalesOrders = () => [
  {
    id: 'sales-001',
    orderNumber: 'SO20241220001',
    customerId: 'customer-001',
    customerName: '北京服装有限公司',
    salesDate: getDateString(25),
    expectedDate: getDateString(23),
    items: [
      {
        id: 'sitem-001',
        productId: 'product-003',
        productName: '染色32支棉纱',
        productCode: 'PROD003',
        colorId: 'color-001',
        colorName: '天蓝色',
        colorCode: 'COL-001',
        batchId: 'batch-006',
        batchCode: 'GH-2024-006',
        quantity: 150,
        unit: 'kg',
        price: 38.0,
        amount: 5700,
      },
    ],
    totalAmount: 5700,
    receivedAmount: 5700,
    unpaidAmount: 0,
    status: '已出库' as const,
    operator: '张三',
    remark: '现货',
    createdAt: getDateTimeString(25),
    updatedAt: getDateTimeString(25),
  },
  {
    id: 'sales-002',
    orderNumber: 'SO20241225002',
    customerId: 'customer-002',
    customerName: '广东批发商行',
    salesDate: getDateString(20),
    expectedDate: getDateString(18),
    items: [
      {
        id: 'sitem-002',
        productId: 'product-003',
        productName: '染色32支棉纱',
        productCode: 'PROD003',
        colorId: 'color-002',
        colorName: '粉红色',
        colorCode: 'COL-002',
        batchId: 'batch-007',
        batchCode: 'GH-2024-007',
        quantity: 150,
        unit: 'kg',
        price: 39.0,
        amount: 5850,
      },
    ],
    totalAmount: 5850,
    receivedAmount: 3000,
    unpaidAmount: 2850,
    status: '已出库' as const,
    operator: '李四',
    remark: '部分付款',
    createdAt: getDateTimeString(20),
    updatedAt: getDateTimeString(20),
  },
  {
    id: 'sales-003',
    orderNumber: 'SO20241228003',
    customerId: 'customer-003',
    customerName: '深圳纺织贸易公司',
    salesDate: getDateString(10),
    expectedDate: getDateString(8),
    items: [
      {
        id: 'sitem-003',
        productId: 'product-003',
        productName: '染色32支棉纱',
        productCode: 'PROD003',
        colorId: 'color-003',
        colorName: '米白色',
        colorCode: 'COL-003',
        batchId: 'batch-008',
        batchCode: 'GH-2024-008',
        quantity: 100,
        unit: 'kg',
        price: 37.5,
        amount: 3750,
      },
    ],
    totalAmount: 3750,
    receivedAmount: 0,
    unpaidAmount: 3750,
    status: '草稿' as const,
    operator: '王五',
    createdAt: getDateTimeString(10),
    updatedAt: getDateTimeString(10),
  },
  {
    id: 'sales-004',
    orderNumber: 'SO20241230004',
    customerId: 'customer-001',
    customerName: '北京服装有限公司',
    salesDate: getDateString(2),
    items: [
      {
        id: 'sitem-004',
        productId: 'product-003',
        productName: '染色32支棉纱',
        productCode: 'PROD003',
        colorId: 'color-001',
        colorName: '天蓝色',
        colorCode: 'COL-001',
        batchId: 'batch-006',
        batchCode: 'GH-2024-006',
        quantity: 200,
        unit: 'kg',
        price: 38.5,
        amount: 7700,
      },
    ],
    totalAmount: 7700,
    receivedAmount: 0,
    unpaidAmount: 7700,
    status: '草稿' as const,
    operator: '赵六',
    createdAt: getDateTimeString(2),
    updatedAt: getDateTimeString(2),
  },
]

// ========== 染色加工单初始数据 ==========
export const initDyeingOrders = () => [
  {
    id: 'dyeing-001',
    orderNumber: 'JG20241210001',
    productId: 'product-001',
    productName: '32支棉纱',
    greyBatchId: 'batch-001',
    greyBatchCode: 'GH-2024-001',
    items: [
      {
        id: 'ditem-001',
        targetColorId: 'color-001',
        targetColorCode: 'COL-001',
        targetColorName: '天蓝色',
        targetColorValue: '#87CEEB',
        quantity: 200,
      },
      {
        id: 'ditem-002',
        targetColorId: 'color-002',
        targetColorCode: 'COL-002',
        targetColorName: '粉红色',
        targetColorValue: '#FFC0CB',
        quantity: 150,
      },
    ],
    factoryId: 'supplier-004',
    factoryName: '山东染色加工厂',
    factoryPhone: '13800138004',
    shipmentDate: getDateString(20),
    expectedCompletionDate: getDateString(15),
    actualCompletionDate: getDateString(13),
    processingPrice: 5.5,
    totalAmount: 1925, // (200 + 150) * 5.5
    status: '已完成' as const,
    operator: '张三',
    remark: '第一批加工',
    createdAt: getDateTimeString(20),
    updatedAt: getDateTimeString(13),
  },
  {
    id: 'dyeing-002',
    orderNumber: 'JG20241215002',
    productId: 'product-001',
    productName: '32支棉纱',
    greyBatchId: 'batch-002',
    greyBatchCode: 'GH-2024-002',
    items: [
      {
        id: 'ditem-003',
        targetColorId: 'color-003',
        targetColorCode: 'COL-003',
        targetColorName: '米白色',
        targetColorValue: '#F5F5DC',
        quantity: 300,
      },
      {
        id: 'ditem-004',
        targetColorId: 'color-004',
        targetColorCode: 'COL-004',
        targetColorName: '浅灰色',
        targetColorValue: '#D3D3D3',
        quantity: 250,
      },
    ],
    factoryId: 'supplier-004',
    factoryName: '山东染色加工厂',
    factoryPhone: '13800138004',
    shipmentDate: getDateString(10),
    expectedCompletionDate: getDateString(5),
    processingPrice: 5.8,
    totalAmount: 3190, // (300 + 250) * 5.8
    status: '加工中' as const,
    operator: '李四',
    remark: '第二批加工',
    createdAt: getDateTimeString(10),
    updatedAt: getDateTimeString(5),
  },
  {
    id: 'dyeing-003',
    orderNumber: 'JG20241220003',
    productId: 'product-002',
    productName: '40支精梳棉纱',
    greyBatchId: 'batch-004',
    greyBatchCode: 'GH-2024-004',
    items: [
      {
        id: 'ditem-005',
        targetColorId: 'color-001',
        targetColorCode: 'COL-001',
        targetColorName: '天蓝色',
        targetColorValue: '#87CEEB',
        quantity: 180,
      },
    ],
    factoryId: 'supplier-004',
    factoryName: '山东染色加工厂',
    factoryPhone: '13800138004',
    shipmentDate: getDateString(3),
    expectedCompletionDate: getDateString(10), // 未来日期
    processingPrice: 6.0,
    totalAmount: 1080, // 180 * 6.0
    status: '待发货' as const,
    operator: '王五',
    createdAt: getDateTimeString(3),
    updatedAt: getDateTimeString(3),
  },
]

// ========== 账款初始数据 ==========
export const initAccountReceivables = () => [
  {
    id: 'receivable-001',
    customerId: 'customer-002',
    customerName: '广东批发商行',
    salesOrderId: 'sales-002',
    salesOrderNumber: 'SO20241225002',
    receivableAmount: 5850,
    receivedAmount: 3000,
    unpaidAmount: 2850,
    accountDate: getDateString(20),
    status: '未结清' as const,
    createdAt: getDateTimeString(20),
    updatedAt: getDateTimeString(18),
  },
]

export const initAccountPayables = () => [
  {
    id: 'payable-001',
    supplierId: 'supplier-001',
    supplierName: '浙江纺织有限公司',
    purchaseOrderId: 'purchase-001',
    purchaseOrderNumber: 'PO20241215001',
    payableAmount: 28500,
    paidAmount: 15000,
    unpaidAmount: 13500,
    accountDate: getDateString(60),
    status: '未结清' as const,
    createdAt: getDateTimeString(60),
    updatedAt: getDateTimeString(55),
  },
  {
    id: 'payable-002',
    supplierId: 'supplier-002',
    supplierName: '江苏纱线厂',
    purchaseOrderId: 'purchase-003',
    purchaseOrderNumber: 'PO20241225003',
    payableAmount: 23040,
    paidAmount: 0,
    unpaidAmount: 23040,
    accountDate: getDateString(30),
    status: '未结清' as const,
    createdAt: getDateTimeString(30),
    updatedAt: getDateTimeString(30),
  },
]

// ========== 盘点单初始数据 ==========
export const initInventoryCheckOrders = () => [
  {
    id: 'check-001',
    orderNumber: 'PD20241201001',
    name: '12月月度盘点',
    warehouse: '1号仓库',
    planDate: getDateString(5),
    items: [
      {
        id: generateId(),
        batchId: 'batch-001',
        batchCode: 'G20241201001',
        productId: 'product-001',
        productName: '32支纯棉纱',
        colorId: 'color-001',
        colorName: '白色',
        colorCode: 'WHITE',
        systemQuantity: 500,
        actualQuantity: 515,
        difference: 15,
        unit: 'kg',
      },
      {
        id: generateId(),
        batchId: 'batch-002',
        batchCode: 'G20241201002',
        productId: 'product-001',
        productName: '32支纯棉纱',
        colorId: 'color-002',
        colorName: '红色',
        colorCode: 'RED',
        systemQuantity: 300,
        actualQuantity: 280,
        difference: -20,
        unit: 'kg',
      },
    ],
    progress: {
      total: 2,
      completed: 2,
    },
    surplus: 15,
    deficit: 20,
    status: '已完成' as const,
    operator: '张三',
    remark: '月度例行盘点',
    createdAt: getDateTimeString(5),
    updatedAt: getDateTimeString(2),
  },
  {
    id: 'check-002',
    orderNumber: 'PD20241128002',
    name: 'A区域抽盘',
    warehouse: '1号仓库',
    planDate: getDateString(8),
    items: [
      {
        id: generateId(),
        batchId: 'batch-003',
        batchCode: 'G20241128001',
        productId: 'product-002',
        productName: '40支纯棉纱',
        colorId: 'color-003',
        colorName: '蓝色',
        colorCode: 'BLUE',
        systemQuantity: 200,
        actualQuantity: 200,
        difference: 0,
        unit: 'kg',
      },
      {
        id: generateId(),
        batchId: 'batch-004',
        batchCode: 'G20241128002',
        productId: 'product-002',
        productName: '40支纯棉纱',
        colorId: 'color-004',
        colorName: '绿色',
        colorCode: 'GREEN',
        systemQuantity: 150,
        actualQuantity: undefined,
        unit: 'kg',
      },
    ],
    progress: {
      total: 2,
      completed: 1,
    },
    surplus: 0,
    deficit: 0,
    status: '盘点中' as const,
    operator: '李四',
    remark: 'A区域抽盘检查',
    createdAt: getDateTimeString(8),
    updatedAt: getDateTimeString(7),
  },
  {
    id: 'check-003',
    orderNumber: 'PD20241125003',
    name: '季度全面盘点',
    warehouse: '全部仓库',
    planDate: getDateString(10),
    items: [],
    progress: {
      total: 0,
      completed: 0,
    },
    surplus: 0,
    deficit: 0,
    status: '计划中' as const,
    operator: '王五',
    remark: '季度全面盘点计划',
    createdAt: getDateTimeString(10),
    updatedAt: getDateTimeString(10),
  },
]

// ========== 打印模板初始数据 ==========
export const initPrintTemplates = () => [
  {
    id: 'template-001',
    name: 'A4 标准销售单',
    type: 'A4模板' as const,
    description: '包含完整商品明细、付款信息、二维码等，适合激光打印机',
    isDefault: true,
    documentType: '销售单' as const,
    pageSettings: {
      width: 210,
      height: 297,
      unit: 'mm' as const,
      marginTop: 10,
      marginRight: 10,
      marginBottom: 10,
      marginLeft: 10,
    },
    titleSettings: {
      enabled: true,
      text: '织云ERP 销售提货单（代合同代欠条）',
      fontSize: 18,
      align: 'center' as const,
    },
    basicInfoFields: {
      documentNumber: true,
      documentDate: true,
      customerName: true,
      contactPerson: true,
      contactPhone: true,
      deliveryAddress: true,
      printDate: true,
    },
    productFields: {
      showTable: true,
      productName: true,
      colorCode: true,
      quantity: true,
      unitPrice: true,
      amount: true,
      batchCode: true,
      remark: true,
      textAlign: 'left' as const,
    },
    summaryFields: {
      subtotal: true,
      totalAmount: true,
      paymentInfo: true,
      creator: true,
      handler: true,
      customerSign: true,
    },
    otherElements: {
      qrcode: true,
      qrcodeCount: 3,
      companyInfo: true,
      cornerMark: false,
      pageNumber: true,
    },
    usageCount: 186,
    createdAt: '2025-11-01T00:00:00.000Z',
    updatedAt: '2025-11-27T14:30:00.000Z',
  },
  {
    id: 'template-002',
    name: '三联销售单',
    type: '三联单' as const,
    description: '三联同时打印（存根联、客户联、记账联），适合针式打印机',
    isDefault: false,
    documentType: '销售单' as const,
    pageSettings: {
      width: 241,
      height: 140,
      marginTop: 10,
      marginRight: 10,
      marginBottom: 10,
      marginLeft: 10,
    },
    titleSettings: {
      enabled: true,
      text: '织云ERP 销售提货单',
      fontSize: 16,
      align: 'center' as const,
    },
    basicInfoFields: {
      documentNumber: true,
      documentDate: true,
      customerName: true,
      contactPerson: true,
      contactPhone: false,
      deliveryAddress: false,
      printDate: true,
    },
    productFields: {
      showTable: true,
      productName: true,
      colorCode: true,
      quantity: true,
      unitPrice: true,
      amount: true,
      batchCode: false,
      remark: false,
      textAlign: 'left' as const,
    },
    summaryFields: {
      subtotal: false,
      totalAmount: true,
      paymentInfo: false,
      creator: true,
      handler: true,
      customerSign: true,
    },
    otherElements: {
      qrcode: false,
      qrcodeCount: 1,
      companyInfo: true,
      cornerMark: false,
      pageNumber: false,
    },
    usageCount: 68,
    createdAt: '2025-11-01T00:00:00.000Z',
    updatedAt: '2025-11-15T10:00:00.000Z',
  },
  {
    id: 'template-003',
    name: 'A4 标准进货单',
    type: 'A4模板' as const,
    description: '进货单专用模板，包含供应商信息、验收栏等',
    isDefault: false,
    documentType: '进货单' as const,
    pageSettings: {
      width: 210,
      height: 297,
      unit: 'mm' as const,
      marginTop: 10,
      marginRight: 10,
      marginBottom: 10,
      marginLeft: 10,
    },
    titleSettings: {
      enabled: true,
      text: '织云ERP 进货单',
      fontSize: 18,
      align: 'center' as const,
    },
    basicInfoFields: {
      documentNumber: true,
      documentDate: true,
      customerName: true,
      contactPerson: true,
      contactPhone: true,
      deliveryAddress: false,
      printDate: true,
    },
    productFields: {
      showTable: true,
      productName: true,
      colorCode: true,
      quantity: true,
      unitPrice: true,
      amount: true,
      batchCode: true,
      remark: true,
      textAlign: 'left' as const,
    },
    summaryFields: {
      subtotal: true,
      totalAmount: true,
      paymentInfo: true,
      creator: true,
      handler: true,
      customerSign: false,
    },
    otherElements: {
      qrcode: true,
      qrcodeCount: 1,
      companyInfo: true,
      cornerMark: false,
      pageNumber: true,
    },
    usageCount: 45,
    createdAt: '2025-11-15T00:00:00.000Z',
    updatedAt: '2025-11-20T09:00:00.000Z',
  },
  {
    id: 'template-004',
    name: '三联进货单',
    type: '三联单' as const,
    description: '三联进货单，适合传统业务流程',
    isDefault: false,
    documentType: '进货单' as const,
    pageSettings: {
      width: 241,
      height: 140,
      marginTop: 10,
      marginRight: 10,
      marginBottom: 10,
      marginLeft: 10,
    },
    titleSettings: {
      enabled: true,
      text: '织云ERP 进货单',
      fontSize: 16,
      align: 'center' as const,
    },
    basicInfoFields: {
      documentNumber: true,
      documentDate: true,
      customerName: true,
      contactPerson: true,
      contactPhone: false,
      deliveryAddress: false,
      printDate: true,
    },
    productFields: {
      showTable: true,
      productName: true,
      colorCode: true,
      quantity: true,
      unitPrice: true,
      amount: true,
      batchCode: false,
      remark: false,
      textAlign: 'left' as const,
    },
    summaryFields: {
      subtotal: false,
      totalAmount: true,
      paymentInfo: false,
      creator: true,
      handler: true,
      customerSign: false,
    },
    otherElements: {
      qrcode: false,
      qrcodeCount: 1,
      companyInfo: true,
      cornerMark: false,
      pageNumber: false,
    },
    usageCount: 23,
    createdAt: '2025-11-15T00:00:00.000Z',
    updatedAt: '2025-11-18T11:00:00.000Z',
  },
]

